### ISSUE TITLE
Categories are not showing up

### ISSUE THREAD

**Issue by bourgeoisrebel** [bourgeoisrebel/everywhere-www#13]
https://www.everywhereitsolutions.com/categories 

Linked to tagging #8

**Comment by bourgeoisrebel** [comment]
Syntax of front matter wrong. Changed to:

```yaml
categories:
- tutorials
tags:
- hugo
- azure
- website
```
